Declarations: заменены токены на id токенов
karupoiss00/compilers pull request #10
Opened 2024-02-26 18:09 UTC by jmv52aof

@karupoiss00

2024-02-27 17:48 UTC, karupoiss00 requested changes

2024-02-27 17:48 UTC, karupoiss00 commented on practice/stend_language/parser/common/identifier.py
> +    return read_token().id == IDENTIFIER
много где встречается подобная конструкция, предлагаю добавить функцию `match_token`, которая будет принимать в себя тип токена и проверять его соответствие текущему токену

2024-02-27 17:48 UTC, karupoiss00 commented on practice/stend_language/parser/declarations/declarations.py
> +    return identifier() and pop_token().id and identifier_list_postfix()
для чего тут получение id? автозамена?)

2024-02-27 17:48 UTC, karupoiss00 commented on practice/stend_language/parser/declarations/declarations.py
> +    return identifier() and pop_token().id and identifier_list_postfix()
поправить везде

2024-02-28 01:39 UTC, jmv52aof commented
@karupoiss00, [исправления](https://github.com/karupoiss00/compilers/pull/10/commits/bac416799afdbbdf655ef339effa207df1455710)

2024-02-28 11:17 UTC, karupoiss00 requested changes

2024-02-28 11:17 UTC, karupoiss00 commented on practice/stend_language/parser/declarations/declarations.tests.py
> +            continue
а где теперь проверка результата парсера? раньше это была проверка на true и false

2024-02-28 13:18 UTC, jmv52aof commented
@karupoiss00, добавил дополнительно тестирование парсера

2024-02-28 19:32 UTC, karupoiss00 approved these changes

2024-02-28 19:45 UTC, merged