Грамматика и реализация DO WHILE STATEMENT
karupoiss00/compilers pull request #12
Opened 2024-02-28 06:48 UTC by danilovvvladimir

2024-02-28 11:20 UTC, karupoiss00 requested changes

2024-02-28 11:20 UTC, karupoiss00 commented on practice/stend_language/parser/list_statements/list_statements.py
> +        read_token() == "DO"
нужно подмержить мастер и проверять через `match_token`, а не строки напрямую

2024-02-28 11:20 UTC, karupoiss00 commented on practice/stend_language/parser/list_statements/list_statements.py
> +        read_token() == "DO"
а ещё нужно покрыть тестами

2024-03-14 04:18 UTC, danilovvvladimir commented on practice/stend_language/parser/list_statements/list_statements.py
> +        read_token() == "DO"
> нужно подмержить мастер и проверять через `match_token`, а не строки напрямую

актуализировал

2024-03-14 04:18 UTC, danilovvvladimir commented on practice/stend_language/parser/list_statements/list_statements.py
> +        read_token() == "DO"
> а ещё нужно покрыть тестами

:(
типо program.tests или какие? их чёт тут многовато

2026-06-07 05:51 UTC, closed without merging